M48
; DRILL file {KiCad 8.0.3} date 2024-07-10T18:00:05+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-10T18:00:05+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1457
%
G90
G05
T1
X8.7008Y-1.7323
T2
X2.3622Y-1.9685
X2.3622Y-10.2362
X14.1732Y-1.9685
X14.1732Y-10.2362
M30
