/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(UdongConfig, UdongConfig, AUTO)


PB_BIND(AnalogSwitchAssignment, AnalogSwitchAssignment, AUTO)


PB_BIND(AnalogSwitchGroup, AnalogSwitchGroup, AUTO)


PB_BIND(RapidTrigger, RapidTrigger, AUTO)


PB_BIND(StaticTrigger, StaticTrigger, AUTO)


PB_BIND(ButtonId, ButtonId, AUTO)


PB_BIND(PushButtonSelector, PushButtonSelector, AUTO)


PB_BIND(DPadButtonSelector, DPadButtonSelector, AUTO)


PB_BIND(ButtonAssignment, ButtonAssignment, AUTO)






