/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(UdongConfig, UdongConfig, 2)


PB_BIND(AnalogSwitchAssignment, AnalogSwitchAssignment, AUTO)


PB_BIND(AnalogSwitchGroup, AnalogSwitchGroup, AUTO)


PB_BIND(RapidTriggerConfig, RapidTriggerConfig, AUTO)


PB_BIND(StaticTriggerConfig, StaticTriggerConfig, AUTO)


PB_BIND(ButtonId, ButtonId, AUTO)


PB_BIND(PushButtonSelector, PushButtonSelector, AUTO)


PB_BIND(DPadButtonSelector, DPadButtonSelector, AUTO)


PB_BIND(ButtonAssignment, ButtonAssignment, AUTO)






#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

